# Comment out to implement Jenkins pipeline for deployment to VPS

# name: deploy to vps
# on:
#     push:
#         branches:
#             - main

# # create a sample for now
# jobs:
#     deploy:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Deploy to VPS
#               uses: appleboy/ssh-action@v1.0.3
#               with:
#                 host: ${{ secrets.VPS_HOST }}
#                 username: ${{ secrets.VPS_USER }}
#                 key: ${{ secrets.VPS_KEY }}
#                 passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
#                 script: |
#                   echo "Deploying to VPS..."
                  
#                   cd /root/test-ci-cd-1

#                   echo "Pulling latest changes from GitHub repository..."
#                   git pull

#                   echo "Building and restarting Docker containers..."
#                   docker-compose down

#                   docker-compose build

#                   docker-compose up -d

#                   echo "Cleaning up dangling Docker images..."
#                   docker images -f "dangling=true" -q | xargs -r docker rmi

#                   echo "Deployment to VPS completed."

